[build]
command = "echo 'Netlify Build Started'"
publish = "."

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/api"
status = 200
force = true

[[redirects]]
from = "/api/upload"
to = "/.netlify/functions/api"
status = 200
force = true