[build]

Build settings (if needed)

command = ""
publish = "/* folder where your index.html is located */"

[functions]

Tell Netlify where your serverless functions are located

directory = "netlify/functions"

This sets the base URL for the functions, accessible as /api/*

The function file name is api.js, so the path will be /api/api

To make it accessible via /api/chat and /api/upload, we use redirects below.

--- Redirects (Crucial for clean URLs) ---

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/api"
status = 200
force = true

[[redirects]]
from = "/api/upload"
to = "/.netlify/functions/api"
status = 200
force = true
